
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyCompanyAttribute("zbundler")]
[assembly: AssemblyConfigurationAttribute("Debug")]
[assembly: AssemblyProductAttribute("zbundler")]
[assembly: AssemblyTitleAttribute("zbundler")]
[assembly: AssemblyVersion("0.4.40")]
[assembly: AssemblyFileVersion("0.4.40")]
